### ISSUE TITLE
Bug in "fix" repository instructions in readme and init.yaml?

### ISSUE THREAD

**Issue by jayrgauthier** [SoftwareAG/sagdevops-cc-docker-builder#1]
When I edit init.yaml to point to Empower for fixes and 10.1, per the readme instructions, I get the error:
ERROR: 400 Bad Request
CCECPTE0006:Invalid repository definition.

Error >>>

Message: Invalid repository definition.
Code: CCECPTE0006
Id: 1509477620754

It seems the portion for "fix" is in error.  I commented that and was able to proceed.

**Comment by mstoffel-sag** [comment]
Same for me. What would be the appropriate settings for fixes?

**Comment by sergeipogrebnyak** [comment]
Will try to look into this sometime soon

**Comment by sergeipogrebnyak** [comment]
Yes, fix repo definition was wrong for Empower since. I was testing against internal and local mirror repos, but not Empower as public 10.1 was not available at the time.
Tested with SDC 10.1 and Empower today. Works for IS Core Fix1
