### ISSUE TITLE
Can't install fixes onto "managed" container

### ISSUE THREAD

**Issue by jayrgauthier** [SoftwareAG/sagdevops-cc-docker-builder#3]
I was able to build and launch all the containers in this example.  Then I configured CC with my Empower credentials and added a fix repo.  I was able to connect to empower for fixes and see the fixes for my installation, but it fails to install fixes, with an error that it is missing some SUM files.  Any ideas?  We should probably ensure that containers made via this cc build template can have fixes applied.  See also other issue about the fix section of the init.yaml file.

**Comment by sergeipogrebnyak** [comment]
Fixed
https://github.com/SoftwareAG/sagdevops-cc-docker-builder/commit/ee90e83dd068ab01f07a9b295ab7683dc6bec2f1
Fix repository definition was wrong
