### ISSUE TITLE
How to point to a mirror repo in the init.yaml file

### ISSUE THREAD

**Issue by HenningWaack** [SoftwareAG/sagdevops-cc-docker-builder#8]
How can I point to a mirro repo in the init.yaml file? It is not described in the readme. 

In general it would be great to get some more information on how this init.yaml file is used and in general about its format.

**Comment by sergeipogrebnyak** [comment]
10.3 supports REPO_* parameters. See https://github.com/SoftwareAG/sagdevops-cc-docker-builder/blob/master/docker-compose.yml#L11 for details
